/*
 * This Java source file was generated by the Gradle 'init' task.
 *
 * This file was disabled as not test are implemented in this project currently.
 */
package test.java.kaica_dun;

/**
import main.java.kaica_dun.App;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}

 */