/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kaica_dun;

import kaica_dun.entities2.TestDb;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class App {
    // This logger has a name so that it can retrieved for use from anywhere in the application.
    private static final Logger LOGGER = LogManager.getLogger("MAIN");

    public static void main(String[] args) throws Exception {
        LOGGER.info("- - - K A I C A - - -");

        //Player player = new Player();
        //makeStaticDungeon msd = new makeStaticDungeon(player);

        //Dungeon d = msd.makeDungeon();

        String[] i = {};
        TestDb.main(i);

        //TestDb testDb = new TestDb();

        //testDb.testDb();
    }


}
