/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kaica_dun;

import kaica_dun.Entities.Item;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Item item = new Item();
    }
}
